filetype off

set rtp+=~/.vim/bundle/Vundle.vim

call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'ervandew/supertab'
call vundle#end()

filetype plugin indent on

let g:SuperTabDefaultCompletionType = "<c-n>"

set ruler
set nocompatible
set showmatch
set incsearch
set hlsearch
set bg=dark
syntax enable
colo monokain
set tabstop=3
set shiftwidth=3
set softtabstop=3
set expandtab
set autoindent
set cindent

au BufWinEnter * let w:m2=matchadd('ErrorMsg', '\%>80v.\+', -1)
autocmd FileType latex,tex,md,markdown setlocal spell
autocmd FileType latex,tex,md,markdown setlocal textwidth=80
